# **NumPy Arrays**

In [1]:
# List using python
my_list = [1,2,3]

In [5]:
# Import NumPy  
import numpy as np

In [7]:
# Creating array from a regular Python list
arr=np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [48]:
# Creating 2d-array from  a regular 2d- Python list
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_arr=np.array(my_mat)
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# To create sequences of numbers, NumPy provides the arange function which is 
# analogous to the Python built-in range, but returns an array
np.arange(0,10,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
# The function zeros creates an array full of zeros
np.zeros(3)

array([0., 0., 0.])

In [47]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# The function ones crates an arry full of ones
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
# linspace is used for creating numeric sequence i.e it creates sequence of 
# evenly spaced numbers structured as a NumPy array.
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [22]:
# The eye tool returns a 2-D array with 1's as the diagonal and 0's elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
# The numpy. random. rand() function creates an array of specified shape and 
# fills it with random values

np.random.rand(5) # 1d array

array([0.59582678, 0.84998178, 0.54932707, 0.05559453, 0.82195989])

In [24]:
np.random.rand(5,5) # 2d array

array([[0.80091107, 0.05424891, 0.16301598, 0.77576206, 0.12012708],
       [0.37973699, 0.66225828, 0.58728271, 0.54452918, 0.34400737],
       [0.34723211, 0.61560674, 0.345057  , 0.44624925, 0.12444165],
       [0.10254242, 0.78065702, 0.1145859 , 0.83306992, 0.32604837],
       [0.28449157, 0.32397391, 0.84649714, 0.7464977 , 0.3922935 ]])

In [25]:
# " The numpy. random. randn() function creates an array of specified shape and 
# fills it with random values as per standard normal distribution "
np.random.randn(2) # 1d array

array([ 0.29224951, -0.79786178])

In [26]:
np.random.randn(4,4) # 2d array

array([[-0.5431313 ,  1.18594408, -0.56830742, -0.49224302],
       [-0.43718842,  0.33156103,  0.06658686, -1.40782067],
       [-0.51971462, -0.26475393, -0.92260825, -1.6515525 ],
       [-0.38818038,  1.37574441, -0.38083613,  0.77691999]])

In [28]:
# np.random.randint() is the function for doing random sampling in numpy and it
# returns an array of specified shape and fills it with random integers form
# low to high i.e in the interval [low, high]
np.random.randint(1,100,10)

array([41, 74, 26, 50, 94, 57, 66, 20, 27, 77])

In [31]:
new_arr=np.arange(25)

In [32]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ran_new_arr=np.random.randint(0,50,10)

In [34]:
ran_new_arr

array([21, 39, 10, 44,  4,  7, 15,  4, 19, 31])

In [35]:
# Gives a new shape to an array without changing its data.
new_arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])