# **Numpy Indexing and Selection**

In [1]:
# Import NumPy
import numpy as np

In [2]:
# Creating an array
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# printing the element at index 8
arr[8]

8

In [5]:
# Slice elements from index 1 to index 5 from the following array.
arr[1:5]

array([1, 2, 3, 4])

In [6]:
# Slice elements from index 0 to index 5 from the following array:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
# Slice elements from the beginning to index 6 (not included)
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
# Slice elements from index 5 to the end of the array
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
# assign  value 100 from index 0 to index 5
arr[0:5]=100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr=np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# creating a view to original array 
slice_of_arr=arr[0:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
# assign value 99 to whole slice_of_arr but this will also change the 
# original array.
slice_of_arr[:]=99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
# original array is also changed.
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
# To copy an actual array not a reference to the original array.
arr_copy=arr.copy()

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:]=10

In [22]:
arr_copy

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])