# **NumPy Indexing and Selection**

In [1]:
# Import NumPy 
import numpy as np

In [2]:
# Creating 2d array 
arr_2d= np.array([[5,10,15],[20,25,30],[35,40,45]])

In [3]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
# Element in the first row and the first column 
# Syntax: array_name[row][column]
arr_2d[0][0]

5

In [5]:
#  Printing the Entire row of index 0
arr_2d[0]

array([ 5, 10, 15])

In [6]:
arr_2d[1][1]

25

In [7]:
arr_2d[2][1]

40

In [9]:
# This is double bracket notation : arr_2d[2][1]
arr_2d[2,1] # This is single bracket notation both are same. 
                            # Syntax: array_name[row,column]

40

In [11]:
# Slicing notation
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [12]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
arr_2d[1:,]

array([[20, 25, 30],
       [35, 40, 45]])

In [14]:
# Creating 1d an array
arr=np.arange(1,11)

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# Giving a condition it return boolean values
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [17]:
bool_arr=arr>5

In [18]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [19]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [20]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [21]:
arr[arr<3]

array([1, 2])

In [22]:
arr_2d=np.arange(50).reshape(5,10)

In [23]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [24]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])