# **Numpy Arrays**



**Stacking together different arrays**

In [1]:
import numpy as np

In [7]:
a=np.arange(1,13).reshape(3,4)

In [8]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
b=np.arange(13,25).reshape(3,4)

In [10]:
b

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [11]:
# np. vstack combines arrays vertically.
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [12]:
#  np. hstack combines NumPy arrays horizontally.
np.hstack((a,b))

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [13]:
# np.concatenate combine arrays horizontally as well as vertically.
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [14]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])



*   When using NumPy vstack, the input array can have different number of rows but same number of columns.


*   When sing NumPy hstack, the input array can have different number of columns but same number of rows



*   np.concatenate behaves depends on how you use the axis parameter in the syntax 



In [15]:
c=np.array([1,2])

In [18]:
c

array([1, 2])

In [17]:
d=np.array([8,9])

In [19]:
d

array([8, 9])

In [21]:
# The function column_stack stacks 1D arrays as columns into a 2D array.
np.column_stack((c,d))

array([[1, 8],
       [2, 9]])

In [22]:
np.hstack((a,b))

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [20]:
# The function column_stack is equivalent to hstack only for 2D arrays
np.column_stack((a,b))

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [28]:
from numpy import newaxis
A=np.array([2,4,6,8])

In [29]:
A

array([2, 4, 6, 8])

In [30]:
# newaxis is used to increase the dimension of the existing array by one more
# dimension, when used once 
# 1d array will become 2d array
# 2d array will become 3d array and so on..
A[newaxis,:] # make it as a row vector by inserting an axis along first dimension

array([[2, 4, 6, 8]])

In [32]:
A[:,newaxis] # make it as a column vector by inserting an axis along second dimension

array([[2],
       [4],
       [6],
       [8]])

**Splitting one array into several smaller ones**

In [40]:
new_arr=np.arange(20).reshape(5,4)

In [41]:
new_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
# hsplit is used to split an arrray along its horizontal axis,either by
# specifying the number of equally shaped arrays to return, or by specifying the
# columns after which the division should occur
np.hsplit(new_arr,2) # split new_arr into 2

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [44]:
np.hsplit(new_arr,(2,3))# Split new_arr after the second and the third column

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]), array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]), array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [45]:
x=np.arange(16.0).reshape(4,4)

In [46]:
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [47]:
np.vsplit(x,2)# vsplit splits along the vertical axis

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]